[features]
seeds = false
[programs.localnet]
conversation = "8xMGj9G2hYRAfgdkG45xqmWCMmh6pb4agu26REJC9LsX"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/muhammadtalhadar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
